-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  signing_keys

CREATE TABLE IF NOT EXISTS signing_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  algo_id BIGINT NOT NULL,                   -- crypto_algorithms (class='sig')
  name VARCHAR(120) NOT NULL,
  public_key BYTEA NOT NULL,
  private_key_enc BYTEA NULL,                -- when stored encrypted locally
  kms_key_id BIGINT NULL,                    -- when stored in KMS/HSM
  origin TEXT NOT NULL DEFAULT 'local',      -- 'local' | 'kms' | 'imported'
  status TEXT NOT NULL DEFAULT 'active',     -- 'active' | 'retired' | 'compromised'
  scope VARCHAR(120) NULL,                   -- e.g. 'audit', 'events', 'assets'
  created_by BIGINT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  activated_at TIMESTAMPTZ(6) NULL,
  retired_at   TIMESTAMPTZ(6) NULL,
  notes TEXT NULL,
  CONSTRAINT uq_signing_keys_name UNIQUE (name),
  CONSTRAINT chk_sk_origin CHECK (origin IN ('local','kms','imported')),
  CONSTRAINT chk_sk_status CHECK (status IN ('active','retired','compromised'))
);
